Style/AsciiComments:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Naming/FileName:
  Exclude:
    - 'lib/growi-image-converter-esa.rb'